
services:
  db:
    container_name: mongo_container
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

  stripe-cli:
    container_name: stripe-cli
    image: stripe/stripe-cli:latest
    stdin_open: true 
    tty: true
    volumes:
      - stripe_config:/root/.config/stripe
    command: listen --forward-to localhost:3000/api/stripe/webhooks
  
  
volumes:
  mongo_data:
  stripe_config: