
services:
  db:
    container_name: mongo_container
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  stripe-cli:
    container_name: stripe-cli
    image: stripe/stripe-cli:latest
    stdin_open: true 
    tty: true
    volumes:
      - stripe_config:/root/.config/stripe 
    command: listen --forward-to host.docker.internal:3000/api/stripe/webhooks
  
  next_dev:
    container_name: next_container
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - stripe-cli
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh 
    stdin_open: true
    tty: true

volumes:
  mongo_data:
  stripe_config: